const fs = require('fs');
const path = require('path');
const axios = require('axios');
const bluebird = require('bluebird');
const ensureDirectoryExistence = (filePath) => {
    var dirname = path.dirname(filePath);
    if (fs.existsSync(dirname)) {
        return true;
    }
    ensureDirectoryExistence(dirname);
    fs.mkdirSync(dirname);
};
const urls = [
// 'https://eso.vse.cz/~duzm00/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~duzm00/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~duzm00/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~duzm00/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~fral06/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~fral06/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~fral06/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~fral06/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~jedv00/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~jedv00/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~jedv00/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~jedv00/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~vavl03/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~vavl03/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~vavl03/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~vavl03/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~potp04/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~potp04/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~potp04/cv05/homework/css/task-grid.css',
// 'https://eso.vse.cz/~potp04/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~horl13/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~horl13/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~horl13/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~horl13/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~ulvo00/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~ulvo00/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~ulvo00/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~ulvo00/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~doss02/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~doss02/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~doss02/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~doss02/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~apai00/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~apai00/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~apai00/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~apai00/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~prod10/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~prod10/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~prod10/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~prod10/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~vecs00/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~vecs00/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~vecs00/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~vecs00/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~stea11/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~stea11/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~stea11/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~stea11/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~pivt02/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~pivt02/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~pivt02/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~pivt02/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~pinl01/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~pinl01/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~pinl01/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~pinl01/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~sikj01/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~sikj01/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~sikj01/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~sikj01/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~dinv00/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~dinv00/cv05/homework/assets-hw/css/styles-grid.css',
// 'https://eso.vse.cz/~dinv00/cv05/homework/styles-page-layout.html',
// 'https://eso.vse.cz/~dinv00/cv05/homework/assets-hw/css/styles-page-layout.css',
// 'https://eso.vse.cz/~kham06/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~kham06/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~kham06/cv05/homework/styles-page-layout.html',
// 'https://eso.vse.cz/~kham06/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~kozo01/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~kozo01/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~kozo01/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~kozo01/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~sinj04/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~sinj04/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~sinj04/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~sinj04/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~zofm00/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~zofm00/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~zofm00/cv05/homework/styles-grid.css',
// 'https://eso.vse.cz/~zofm00/cv05/homework/styles-page-layout.css',
// 'https://eso.vse.cz/~novd35/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~novd35/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~novd35/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~novd35/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~mrkm00/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~mrkm00/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~mrkm00/cv05/homework/styles-page-layout.html',
// 'https://eso.vse.cz/~mrkm00/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~novb12/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~novb12/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~novb12/cv05/homework/styles-page-layout.html',
// 'https://eso.vse.cz/~novb12/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~toho00/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~toho00/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~toho00/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~toho00/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~gerv03/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~gerv03/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~gerv03/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~gerv03/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~ruzv01/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~ruzv01/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~ruzv01/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~ruzv01/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~bejt02/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~bejt02/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~bejt02/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~bejt02/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~vetj00/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~vetj00/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~vetj00/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~vetj00/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~zidd00/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~zidd00/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~zidd00/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~zidd00/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~kyvt00/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~kyvt00/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~kyvt00/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~kyvt00/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~ngut37/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~ngut37/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~ngut37/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~ngut37/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~pryp00/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~pryp00/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~pryp00/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~pryp00/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~seip00/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~seip00/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~seip00/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~seip00/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~podj00/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~podj00/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~podj00/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~podj00/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~fouf00/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~fouf00/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~fouf00/cv05/homework/styles-page-layout.html',
// 'https://eso.vse.cz/~fouf00/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~posn01/cv05/homework/styles-page-layout.html',
// 'https://eso.vse.cz/~posn01/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~posn01/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~posn01/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~stey04/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~stey04/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~stey04/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~stey04/cv05/homework/css/styles-page-layout.css',
// 'https://eso.vse.cz/~mikt05/cv05/homework/task-grid.html',
// 'https://eso.vse.cz/~mikt05/cv05/homework/css/styles-grid.css',
// 'https://eso.vse.cz/~mikt05/cv05/homework/task-page-layout.html',
// 'https://eso.vse.cz/~mikt05/cv05/homework/css/styles-page-layout.css',
'https://eso.vse.cz/~pivt02/cv05/homework/css/styles-grid.css',
'https://eso.vse.cz/~sikj01/cv05/homework/css/styles-grid.css',
'https://eso.vse.cz/~dinv00/cv05/homework/styles-page-layout.html',
'https://eso.vse.cz/~kham06/cv05/homework/styles-page-layout.html',
'https://eso.vse.cz/~zofm00/cv05/homework/task-grid.html',
'https://eso.vse.cz/~toho00/cv05/homework/task-page-layout.html',
'https://eso.vse.cz/~bejt02/cv05/homework/task-grid.html',
'https://eso.vse.cz/~fouf00/cv05/homework/styles-page-layout.html',
'https://eso.vse.cz/~mikt05/cv05/homework/css/styles-page-layout.css',
];

bluebird.each(urls, (url) => {
    return axios.get(url).then((resp) => {
        const parts = url.split('/');
        const xname = parts[3].replace('~', '');
        const file = parts.slice(6).join('/');
        const filePath = `./original/${xname}/${file}`;
        ensureDirectoryExistence(filePath);
        fs.writeFileSync(filePath, resp.data);
    }).catch((err) => {
        console.log(url);
    });
});
